### ISSUE TITLE
Not working with rust 13.0?

### ISSUE THREAD

**Issue by nomoon** [steveklabnik/ruby-sys#12]
I'm getting a silent failure running a native extension with Rust 1.13. My public external "init" function fires and returns, but none of its calls to Ruby (rb_define_module, rb_define_method) seem to have any effect. Not getting any errors either. Everything runs perfectly with Rust 1.12.1.

**Comment by d-unsed** [comment]
Can you please provide an example of both Ruby and Rust code which fails to work? Also would be helpful to know the OS and Ruby versions.

I haven't noticed any issues with the exising apps after switching to 1.13.0.

**Comment by nomoon** [comment]
I have a skeleton test-case here: https://github.com/nomoon/ruby_sys_test

**Comment by nomoon** [comment]
OSX Sierra with Ruby 2.3.3

Output with Rust 1.12.1:
```
> rake
checking for cargo... yes
~/.cargo/bin/cargo build --release
   Compiling libc v0.2.17
   Compiling ruby-sys v0.2.17
   Compiling ruby_sys_test v0.0.0 (~/ruby-sys-test)
    Finished release [optimized] target(s) in 2.40 secs
1. RubySysTest.load_rust() should return 255:
255

::RubySysTest::Rust should be defined:
yes

::RubySysTestRust should be defined:
yes
```

Output with Rust 1.13 (stable)
```
> rake
checking for cargo... yes
~/.cargo/bin/cargo build --release
   Compiling ruby-sys v0.2.17
   Compiling libc v0.2.17
   Compiling ruby_sys_test v0.0.0 (~/ruby-sys-test)
    Finished release [optimized] target(s) in 1.74 secs
1. RubySysTest.load_rust() should return 255:
255

::RubySysTest::Rust should be defined:
no

::RubySysTestRust should be defined:
no
```

Rust installation is managed via Rustup. Identical results with Ruby 2.3.1 and 2.4.0-preview3.

So as you can see, the "init" function returns the proper number, but none of the Ruby API functions has any effect, nor causes an error.

**Comment by nomoon** [comment]
So as you can see, the "init" function returns the proper number, but none of the Ruby API functions has any effect, nor causes an error.

**Comment by d-unsed** [comment]
I am not able to test it right now, but I'm pretty sure that the problem is caused by converting `&str` to `*const c_char`.

https://github.com/nomoon/ruby_sys_test/blob/master/src/lib.rs#L7-L9

```rust
fn str_to_cstrp(s: &str) -> *const c_char {
    CString::new(s).unwrap().as_ptr()
}
```

`CString` is destroyed when it goes out of the scope and the pointer returned by `as_str()` (and by `str_to_cstrp`) points to invalid memory. I've noticed that on Linux this behaviour causes segfaults, but on Mac OS X programs continue their execution.

The solution should look like this:

```rust
// return CString instead of *const c_char
fn str_to_cstrp(s: &str) -> CString {
    CString::new(s).unwrap()
}

fn define_module(name: &str) -> Value {
    let c_strp = str_to_cstrp(name); // get CString and its lifetime is bound to the whole `define_module` function
    unsafe { class::rb_define_module(c_strp.as_ptr()) } // pass pointer to ruby
}

fn define_module_under(parent: Value, name: &str) -> Value {
    let c_strp = str_to_cstrp(name);
    unsafe { class::rb_define_module_under(parent, c_strp.as_ptr()) }
}
```

Please let me know if it works for you!

**Comment by nomoon** [comment]
This was indeed the problem. Any idea why 1.12.1 wasn't causing the issue as well?

**Comment by d-unsed** [comment]
I believe there were some changes in Rust 1.13.0 comparing to 1.12.1 which caused this behaviour.
