### ISSUE TITLE
Basic how-to documentation

### ISSUE THREAD

**Issue by danielpclark** [steveklabnik/ruby-sys#3]
Hey Steve, great work!  I've been looking at the various ruby-rust-ruby crates and what I can't find is documentation on using them.

Currently I'm looking to do something that may be somewhat simple as returning an Array from Rust to Ruby with FFI.  I've opened an issue https://github.com/danielpclark/faster_path/issues/6 to discuss that on my project.

Basically I'm not fully aware of what problems this project addresses.  I don't see howtos or examples of it, or basic documentation.  I'm thinking I'd like to use this crate, but I don't know where to begin.

**Comment by steveklabnik** [comment]
> Basically I'm not fully aware of what problems this project addresses

Like most `-sys` crates, it boils down to "a minimum, unsafe wrapper over the library." So you get unsafe functions which map directly to MRI's cext functions.  `ruru` builds on top of this to give you a nicer API; helix conceptually does too, but doesn't literally use this library, they have their own.

I haven't had any time to write the docs, but if you have specific questions, I'd be happy to answer.
